### ISSUE TITLE
Throw error when `CONSUMER_CLIENT_TYPE` is missing

### ISSUE THREAD

**Issue by niels-s** [blendle/go-streamprocessor#107]
There was an undocumented breaking change from `v2.0.0-beta4` to `v2.0.0` somewhere. The type of consumer changed from `STREAMCLIENT_CONSUMER ` to `CONSUMER_CLIENT_TYPE `.
And for some reason there wasn't any error thrown during setup: https://github.com/blendle/go-streamprocessor/blob/master/streamclient/consumer.go#L14-L16.

So we expect the stdin detection which is done https://github.com/blendle/go-streamprocessor/blob/master/streamclient/consumer.go#L35-L37 and  https://github.com/blendle/go-streamprocessor/blob/master/streamclient/consumer.go#L42-L53 doesn't work how it suppose to. At least not in a containerized environment so we need to fix that since now the processor would just finish properly with exit code 0 and mark the pod as completed in k8s.

**Comment by JeanMertz** [comment]
Some references:

* https://github.com/blendle/go-streamprocessor/pull/17
* https://github.com/blendle/go-streamprocessor/pull/19
* https://github.com/blendle/go-streamprocessor/pull/90
